# ═══════════════════════════════════════════
#          xdGens  -  config.yml
# ═══════════════════════════════════════════

# ── Weizenfeld ──────────────────────────────
field:
  world: world          # Name der Welt
  center-x: 0          # Mittelpunkt X
  center-z: 0          # Mittelpunkt Z
  radius: 25           # Feld = (2*radius+1) x (2*radius+1) = 51x51 Blöcke
  y: 64                # Y-Koordinate des Farmland-Blocks
  regrow-delay-ticks: 100   # Wie lange bis Weizen nachwächst (20 Ticks = 1 Sek)

# ── Weizen Rewards ──────────────────────────
rewards:
  wheat:
    tokens:
      min: 3
      max: 10
    xp:
      min: 8.0
      max: 16.0

# ── Verkaufspreise ──────────────────────────
sell:
  wheat:
    price: 20.0
  compressed_wheat_block:
    price: 1500.0
  enchanted_wheat_bale:
    price: 120000.0
