# ═══════════════════════════════════════════
#          xdGens  -  config.yml
# ═══════════════════════════════════════════

# ── Weizenfeld ──────────────────────────────
field:
  world: world
  center-x: 0
  center-z: 0
  radius: 25
  y: 64
  regrow-delay-ticks: 100

# ── Weizen Rewards ──────────────────────────
rewards:
  wheat:
    tokens:
      min: 3
      max: 10
    xp:
      min: 8.0
      max: 16.0

# ── Verkaufspreise ──────────────────────────
sell:
  wheat:
    price: 30.0
  compressed_wheat_block:
    price: 2200.0
  enchanted_wheat_bale:
    price: 180000.0
